// Mocks generated by Mockito 5.4.6 from annotations
// in shortest_app/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter/foundation.dart' as _i18;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:http/http.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;
import 'package:pocketbase/src/auth_store.dart' as _i4;
import 'package:pocketbase/src/client.dart' as _i19;
import 'package:pocketbase/src/dtos/record_model.dart' as _i21;
import 'package:pocketbase/src/services/backup_service.dart' as _i11;
import 'package:pocketbase/src/services/batch_service.dart' as _i15;
import 'package:pocketbase/src/services/collection_service.dart' as _i5;
import 'package:pocketbase/src/services/cron_service.dart' as _i12;
import 'package:pocketbase/src/services/file_service.dart' as _i6;
import 'package:pocketbase/src/services/health_service.dart' as _i10;
import 'package:pocketbase/src/services/log_service.dart' as _i9;
import 'package:pocketbase/src/services/realtime_service.dart' as _i7;
import 'package:pocketbase/src/services/record_service.dart' as _i14;
import 'package:pocketbase/src/services/settings_service.dart' as _i8;
import 'package:shortest_app/infrastructure/data/client/dio_client.dart'
    as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_1 extends _i1.SmartFake implements _i3.IOSOptions {
  _FakeIOSOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_2 extends _i1.SmartFake
    implements _i3.AndroidOptions {
  _FakeAndroidOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_3 extends _i1.SmartFake implements _i3.LinuxOptions {
  _FakeLinuxOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_4 extends _i1.SmartFake
    implements _i3.WindowsOptions {
  _FakeWindowsOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_5 extends _i1.SmartFake implements _i3.WebOptions {
  _FakeWebOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_6 extends _i1.SmartFake implements _i3.MacOsOptions {
  _FakeMacOsOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthStore_7 extends _i1.SmartFake implements _i4.AuthStore {
  _FakeAuthStore_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionService_8 extends _i1.SmartFake
    implements _i5.CollectionService {
  _FakeCollectionService_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileService_9 extends _i1.SmartFake implements _i6.FileService {
  _FakeFileService_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeService_10 extends _i1.SmartFake
    implements _i7.RealtimeService {
  _FakeRealtimeService_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsService_11 extends _i1.SmartFake
    implements _i8.SettingsService {
  _FakeSettingsService_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogService_12 extends _i1.SmartFake implements _i9.LogService {
  _FakeLogService_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthService_13 extends _i1.SmartFake
    implements _i10.HealthService {
  _FakeHealthService_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackupService_14 extends _i1.SmartFake
    implements _i11.BackupService {
  _FakeBackupService_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCronService_15 extends _i1.SmartFake implements _i12.CronService {
  _FakeCronService_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_16 extends _i1.SmartFake implements _i13.Client {
  _FakeClient_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecordService_17 extends _i1.SmartFake
    implements _i14.RecordService {
  _FakeRecordService_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_18 extends _i1.SmartFake implements Uri {
  _FakeUri_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchService_19 extends _i1.SmartFake implements _i15.BatchService {
  _FakeBatchService_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_20<T1> extends _i1.SmartFake implements _i16.Future<T1> {
  _FakeFuture_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IDioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDioClient extends _i1.Mock implements _i17.IDioClient {
  MockIDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i2.Response<dynamic>> getRequest(
    String? endpoint, {
    Map<String, dynamic>? queryParams,
    _i2.FormData? formData,
    bool? isMultiPart = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRequest,
              [endpoint],
              {
                #queryParams: queryParams,
                #formData: formData,
                #isMultiPart: isMultiPart,
              },
            ),
            returnValue: _i16.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #getRequest,
                  [endpoint],
                  {
                    #queryParams: queryParams,
                    #formData: formData,
                    #isMultiPart: isMultiPart,
                  },
                ),
              ),
            ),
          )
          as _i16.Future<_i2.Response<dynamic>>);

  @override
  _i16.Future<_i2.Response<dynamic>> postRequest(
    String? endpoint, {
    Map<String, dynamic>? bodyParams,
    Map<String, dynamic>? queryParams,
    _i2.FormData? formData,
    bool? isMultiPart = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postRequest,
              [endpoint],
              {
                #bodyParams: bodyParams,
                #queryParams: queryParams,
                #formData: formData,
                #isMultiPart: isMultiPart,
              },
            ),
            returnValue: _i16.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #postRequest,
                  [endpoint],
                  {
                    #bodyParams: bodyParams,
                    #queryParams: queryParams,
                    #formData: formData,
                    #isMultiPart: isMultiPart,
                  },
                ),
              ),
            ),
          )
          as _i16.Future<_i2.Response<dynamic>>);

  @override
  _i16.Future<_i2.Response<dynamic>> deleteRequest(
    String? endpoint, {
    Map<String, dynamic>? bodyParams,
    _i2.FormData? formData,
    bool? isMultiPart = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteRequest,
              [endpoint],
              {
                #bodyParams: bodyParams,
                #formData: formData,
                #isMultiPart: isMultiPart,
              },
            ),
            returnValue: _i16.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #deleteRequest,
                  [endpoint],
                  {
                    #bodyParams: bodyParams,
                    #formData: formData,
                    #isMultiPart: isMultiPart,
                  },
                ),
              ),
            ),
          )
          as _i16.Future<_i2.Response<dynamic>>);

  @override
  _i16.Future<_i2.Response<dynamic>> patchRequest(
    String? endpoint, {
    Map<String, dynamic>? bodyParams,
    Map<String, dynamic>? queryParams,
    _i2.FormData? formData,
    bool? isMultiPart = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchRequest,
              [endpoint],
              {
                #bodyParams: bodyParams,
                #queryParams: queryParams,
                #formData: formData,
                #isMultiPart: isMultiPart,
              },
            ),
            returnValue: _i16.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #patchRequest,
                  [endpoint],
                  {
                    #bodyParams: bodyParams,
                    #queryParams: queryParams,
                    #formData: formData,
                    #isMultiPart: isMultiPart,
                  },
                ),
              ),
            ),
          )
          as _i16.Future<_i2.Response<dynamic>>);

  @override
  _i16.Future<_i2.Response<_i2.ResponseBody>> getRequestStream(
    String? endpoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? headers,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRequestStream,
              [endpoint],
              {
                #queryParams: queryParams,
                #headers: headers,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i16.Future<_i2.Response<_i2.ResponseBody>>.value(
              _FakeResponse_0<_i2.ResponseBody>(
                this,
                Invocation.method(
                  #getRequestStream,
                  [endpoint],
                  {
                    #queryParams: queryParams,
                    #headers: headers,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i16.Future<_i2.Response<_i2.ResponseBody>>);

  @override
  _i16.Future<_i2.Response<_i2.ResponseBody>> postRequestStream(
    String? endpoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? bodyParams,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postRequestStream,
              [endpoint],
              {
                #queryParams: queryParams,
                #headers: headers,
                #bodyParams: bodyParams,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i16.Future<_i2.Response<_i2.ResponseBody>>.value(
              _FakeResponse_0<_i2.ResponseBody>(
                this,
                Invocation.method(
                  #postRequestStream,
                  [endpoint],
                  {
                    #queryParams: queryParams,
                    #headers: headers,
                    #bodyParams: bodyParams,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i16.Future<_i2.Response<_i2.ResponseBody>>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i3.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_1(this, Invocation.getter(#iOptions)),
          )
          as _i3.IOSOptions);

  @override
  _i3.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_2(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i3.AndroidOptions);

  @override
  _i3.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_3(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i3.LinuxOptions);

  @override
  _i3.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_4(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i3.WindowsOptions);

  @override
  _i3.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_5(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i3.WebOptions);

  @override
  _i3.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_6(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i3.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i18.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i18.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> write({
    required String? key,
    required String? value,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<String?> read({
    required String? key,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<String?>.value(),
          )
          as _i16.Future<String?>);

  @override
  _i16.Future<bool> containsKey({
    required String? key,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<void> delete({
    required String? key,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<Map<String, String>> readAll({
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i16.Future<Map<String, String>>);

  @override
  _i16.Future<void> deleteAll({
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i16.Future<bool?>.value(),
          )
          as _i16.Future<bool?>);
}

/// A class which mocks [PocketBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPocketBase extends _i1.Mock implements _i19.PocketBase {
  MockPocketBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseURL =>
      (super.noSuchMethod(
            Invocation.getter(#baseURL),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#baseURL),
            ),
          )
          as String);

  @override
  String get lang =>
      (super.noSuchMethod(
            Invocation.getter(#lang),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#lang),
            ),
          )
          as String);

  @override
  _i4.AuthStore get authStore =>
      (super.noSuchMethod(
            Invocation.getter(#authStore),
            returnValue: _FakeAuthStore_7(this, Invocation.getter(#authStore)),
          )
          as _i4.AuthStore);

  @override
  _i5.CollectionService get collections =>
      (super.noSuchMethod(
            Invocation.getter(#collections),
            returnValue: _FakeCollectionService_8(
              this,
              Invocation.getter(#collections),
            ),
          )
          as _i5.CollectionService);

  @override
  _i6.FileService get files =>
      (super.noSuchMethod(
            Invocation.getter(#files),
            returnValue: _FakeFileService_9(this, Invocation.getter(#files)),
          )
          as _i6.FileService);

  @override
  _i7.RealtimeService get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeService_10(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i7.RealtimeService);

  @override
  _i8.SettingsService get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettingsService_11(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i8.SettingsService);

  @override
  _i9.LogService get logs =>
      (super.noSuchMethod(
            Invocation.getter(#logs),
            returnValue: _FakeLogService_12(this, Invocation.getter(#logs)),
          )
          as _i9.LogService);

  @override
  _i10.HealthService get health =>
      (super.noSuchMethod(
            Invocation.getter(#health),
            returnValue: _FakeHealthService_13(
              this,
              Invocation.getter(#health),
            ),
          )
          as _i10.HealthService);

  @override
  _i11.BackupService get backups =>
      (super.noSuchMethod(
            Invocation.getter(#backups),
            returnValue: _FakeBackupService_14(
              this,
              Invocation.getter(#backups),
            ),
          )
          as _i11.BackupService);

  @override
  _i12.CronService get crons =>
      (super.noSuchMethod(
            Invocation.getter(#crons),
            returnValue: _FakeCronService_15(this, Invocation.getter(#crons)),
          )
          as _i12.CronService);

  @override
  _i13.Client Function() get httpClientFactory =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientFactory),
            returnValue:
                () =>
                    _FakeClient_16(this, Invocation.getter(#httpClientFactory)),
          )
          as _i13.Client Function());

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i14.RecordService get admins =>
      (super.noSuchMethod(
            Invocation.getter(#admins),
            returnValue: _FakeRecordService_17(
              this,
              Invocation.getter(#admins),
            ),
          )
          as _i14.RecordService);

  @override
  set baseURL(String? _baseURL) => super.noSuchMethod(
    Invocation.setter(#baseURL, _baseURL),
    returnValueForMissingStub: null,
  );

  @override
  set lang(String? _lang) => super.noSuchMethod(
    Invocation.setter(#lang, _lang),
    returnValueForMissingStub: null,
  );

  @override
  set authStore(_i4.AuthStore? _authStore) => super.noSuchMethod(
    Invocation.setter(#authStore, _authStore),
    returnValueForMissingStub: null,
  );

  @override
  set collections(_i5.CollectionService? _collections) => super.noSuchMethod(
    Invocation.setter(#collections, _collections),
    returnValueForMissingStub: null,
  );

  @override
  set files(_i6.FileService? _files) => super.noSuchMethod(
    Invocation.setter(#files, _files),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i7.RealtimeService? _realtime) => super.noSuchMethod(
    Invocation.setter(#realtime, _realtime),
    returnValueForMissingStub: null,
  );

  @override
  set settings(_i8.SettingsService? _settings) => super.noSuchMethod(
    Invocation.setter(#settings, _settings),
    returnValueForMissingStub: null,
  );

  @override
  set logs(_i9.LogService? _logs) => super.noSuchMethod(
    Invocation.setter(#logs, _logs),
    returnValueForMissingStub: null,
  );

  @override
  set health(_i10.HealthService? _health) => super.noSuchMethod(
    Invocation.setter(#health, _health),
    returnValueForMissingStub: null,
  );

  @override
  set backups(_i11.BackupService? _backups) => super.noSuchMethod(
    Invocation.setter(#backups, _backups),
    returnValueForMissingStub: null,
  );

  @override
  set crons(_i12.CronService? _crons) => super.noSuchMethod(
    Invocation.setter(#crons, _crons),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientFactory(_i13.Client Function()? _httpClientFactory) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientFactory, _httpClientFactory),
        returnValueForMissingStub: null,
      );

  @override
  set baseUrl(String? v) => super.noSuchMethod(
    Invocation.setter(#baseUrl, v),
    returnValueForMissingStub: null,
  );

  @override
  _i14.RecordService collection(String? collectionIdOrName) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [collectionIdOrName]),
            returnValue: _FakeRecordService_17(
              this,
              Invocation.method(#collection, [collectionIdOrName]),
            ),
          )
          as _i14.RecordService);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );

  @override
  String filter(String? expr, [Map<String, dynamic>? query = const {}]) =>
      (super.noSuchMethod(
            Invocation.method(#filter, [expr, query]),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.method(#filter, [expr, query]),
            ),
          )
          as String);

  @override
  Uri getFileUrl(
    _i21.RecordModel? record,
    String? filename, {
    String? thumb,
    String? token,
    Map<String, dynamic>? query = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFileUrl,
              [record, filename],
              {#thumb: thumb, #token: token, #query: query},
            ),
            returnValue: _FakeUri_18(
              this,
              Invocation.method(
                #getFileUrl,
                [record, filename],
                {#thumb: thumb, #token: token, #query: query},
              ),
            ),
          )
          as Uri);

  @override
  Uri buildUrl(
    String? path, [
    Map<String, dynamic>? queryParameters = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#buildUrl, [path, queryParameters]),
            returnValue: _FakeUri_18(
              this,
              Invocation.method(#buildUrl, [path, queryParameters]),
            ),
          )
          as Uri);

  @override
  Uri buildURL(
    String? path, [
    Map<String, dynamic>? queryParameters = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#buildURL, [path, queryParameters]),
            returnValue: _FakeUri_18(
              this,
              Invocation.method(#buildURL, [path, queryParameters]),
            ),
          )
          as Uri);

  @override
  _i15.BatchService createBatch() =>
      (super.noSuchMethod(
            Invocation.method(#createBatch, []),
            returnValue: _FakeBatchService_19(
              this,
              Invocation.method(#createBatch, []),
            ),
          )
          as _i15.BatchService);

  @override
  _i16.Future<T> send<T extends dynamic>(
    String? path, {
    String? method = 'GET',
    Map<String, String>? headers = const {},
    Map<String, dynamic>? query = const {},
    Map<String, dynamic>? body = const {},
    List<_i13.MultipartFile>? files = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #send,
              [path],
              {
                #method: method,
                #headers: headers,
                #query: query,
                #body: body,
                #files: files,
              },
            ),
            returnValue:
                _i20.ifNotNull(
                  _i20.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #send,
                      [path],
                      {
                        #method: method,
                        #headers: headers,
                        #query: query,
                        #body: body,
                        #files: files,
                      },
                    ),
                  ),
                  (T v) => _i16.Future<T>.value(v),
                ) ??
                _FakeFuture_20<T>(
                  this,
                  Invocation.method(
                    #send,
                    [path],
                    {
                      #method: method,
                      #headers: headers,
                      #query: query,
                      #body: body,
                      #files: files,
                    },
                  ),
                ),
          )
          as _i16.Future<T>);
}

/// A class which mocks [AuthStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStore extends _i1.Mock implements _i4.AuthStore {
  MockAuthStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get token =>
      (super.noSuchMethod(
            Invocation.getter(#token),
            returnValue: _i20.dummyValue<String>(
              this,
              Invocation.getter(#token),
            ),
          )
          as String);

  @override
  _i16.Stream<_i4.AuthStoreEvent> get onChange =>
      (super.noSuchMethod(
            Invocation.getter(#onChange),
            returnValue: _i16.Stream<_i4.AuthStoreEvent>.empty(),
          )
          as _i16.Stream<_i4.AuthStoreEvent>);

  @override
  bool get isValid =>
      (super.noSuchMethod(Invocation.getter(#isValid), returnValue: false)
          as bool);

  @override
  void save(String? newToken, _i21.RecordModel? newRecord) =>
      super.noSuchMethod(
        Invocation.method(#save, [newToken, newRecord]),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}
